# Generated by Django 3.0.5 on 2020-06-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumimagenes',
            name='imagenes',
            field=models.ImageField(upload_to='Noticias/'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='img_portada',
            field=models.ImageField(upload_to='Noticias/'),
        ),
    ]
