# Generated by Django 3.0.5 on 2020-07-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0006_auto_20200610_2137'),
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='aprobar',
            field=models.CharField(default='si', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='mascotas',
            field=models.ManyToManyField(blank=True, related_name='Mascota', to='mascota.Mascota'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(default='adoptante', max_length=20),
            preserve_default=False,
        ),
    ]
