# Generated by Django 3.0.5 on 2020-07-04 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0007_auto_20200703_2348'),
        ('adopcion', '0002_auto_20200703_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreSolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mascota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PreMascota', to='mascota.Mascota')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adopcion.Persona')),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adopcion.Solicitud')),
            ],
        ),
    ]
