# Generated by Django 3.0.5 on 2020-07-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0007_auto_20200703_2348'),
        ('adopcion', '0004_auto_20200705_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='presolicitud',
            name='mascota',
            field=models.ManyToManyField(blank=True, related_name='PreMascota', to='mascota.Mascota'),
        ),
        migrations.AddField(
            model_name='presolicitud',
            name='persona',
            field=models.ManyToManyField(blank=True, related_name='Persona', to='adopcion.Persona'),
        ),
        migrations.AddField(
            model_name='presolicitud',
            name='solicitud',
            field=models.ManyToManyField(blank=True, related_name='Solicitud', to='adopcion.Solicitud'),
        ),
    ]
