# Generated by Django 3.0.5 on 2020-07-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0007_auto_20200703_2348'),
        ('adopcion', '0005_auto_20200705_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presolicitud',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='presolicitud',
            name='solicitud',
        ),
        migrations.AddField(
            model_name='presolicitud',
            name='apellidos',
            field=models.CharField(default='default', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presolicitud',
            name='aprobar',
            field=models.CharField(default='false', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presolicitud',
            name='domicilio',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presolicitud',
            name='edad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presolicitud',
            name='edad_aproximada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presolicitud',
            name='email',
            field=models.EmailField(default='default', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presolicitud',
            name='especie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='presolicitud',
            name='fecha_rescate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presolicitud',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='Mascotas/'),
        ),
        migrations.AddField(
            model_name='presolicitud',
            name='nombre',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presolicitud',
            name='nombre_mascota',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='presolicitud',
            name='numero_mascotas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presolicitud',
            name='raza',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='presolicitud',
            name='razones',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presolicitud',
            name='sexo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='presolicitud',
            name='telefono',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presolicitud',
            name='tipo',
            field=models.CharField(default='adoptante', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presolicitud',
            name='vacuna',
            field=models.ManyToManyField(blank=True, null=True, related_name='Vacuna', to='mascota.Vacuna'),
        ),
    ]
