# Generated by Django 3.0.5 on 2020-07-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0006_auto_20200705_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='presolicitud',
            name='reseña',
            field=models.CharField(default='Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cum architecto quibusdam vero quasi sapiente. Consequuntur modi, quidem, ea alias beatae rem commodi in minus facilis doloremque cumque deserunt odio at?', max_length=580),
            preserve_default=False,
        ),
    ]
