# Generated by Django 3.0.5 on 2020-07-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0007_presolicitud_reseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presolicitud',
            name='reseña',
            field=models.TextField(max_length=580),
        ),
    ]
