# Generated by Django 3.0.5 on 2020-07-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0009_auto_20200705_1705'),
        ('adopcion', '0008_auto_20200705_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presolicitud',
            name='mascota',
            field=models.ManyToManyField(blank=True, null=True, related_name='PreMascota', to='mascota.Mascota'),
        ),
    ]
