# Generated by Django 3.0.5 on 2020-05-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_auto_20200516_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='categoria',
            field=models.ManyToManyField(blank=True, related_name='categoria', to='mascota.Categoria'),
        ),
    ]
