# Generated by Django 3.0.5 on 2020-06-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0004_auto_20200608_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(upload_to='static/media/Mascotas/'),
        ),
    ]
