# Generated by Django 3.0.5 on 2020-06-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0005_auto_20200610_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(upload_to='Mascotas/'),
        ),
    ]
