# Generated by Django 3.0.5 on 2020-07-04 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_auto_20200703_2348'),
        ('mascota', '0006_auto_20200610_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='padrino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='padrino', to='adopcion.Persona'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adoptante', to='adopcion.Persona'),
        ),
    ]
